modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="watercollector" #mandatory
version="1.0.0" #mandatory
displayName="Watercollector" #mandatory
logoFile="watercondenser.logo.png" #optional
credits="ITank mod for render code." #optional
authors="Leclowndu93150, thepigcat, oierbravo" #optional
description='''
Simple water generator block.
'''

[[dependencies.watercollector]]
modId = "forge"
mandatory = true
versionRange="[47.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.watercollector]]
modId = "minecraft"
mandatory = true
versionRange="[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
