modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="watercondenser" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Watercondenser" #mandatory
logoFile="watercondenser.logo.png" #optional
credits="ITank mod for render code." #optional
authors="oierbravo" #optional
description='''
Simple water generator block.
'''

[[dependencies.watercondenser]]
modId = "forge"
mandatory = true
versionRange="[47.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.watercondenser]]
modId = "minecraft"
mandatory = true
versionRange="[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
